config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :post_images do
  	resource :post_comments, only: [:create]
  	resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update] do
  	get :search, on: :collection
  end

  root "home#index"
  get "home/about" => "home#about"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :post_image
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
	belongs_to :user
	belongs_to :post_image

	validates :comment, presence: true, length: { in: 2..50 }

end

app/models/post_image.rb
class PostImage < ApplicationRecord
	belongs_to :user
	has_many :post_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	has_many :post_image_tag_relations, dependent: :destroy
	has_many :tags, through: :post_image_tag_relations, dependent: :destroy
	attachment :image
	validates :title, presence: true
	validates :caption, presence: true

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end
end

app/models/post_image_tag_relation.rb
class PostImageTagRelation < ApplicationRecord
  belongs_to :post_image
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :post_image_tag_relations, dependent: :destroy
	has_many :post_images, through: :post_image_tag_relations, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :post_images, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  attachment :user_image_id
  validates :name, presence: true
  validates :introduction, length: { in: 1..300 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
	before_action :authenticate_user!
	
	def after_sign_in_path_for(resource)
		post_images_path
	end
	def after_sign_out_path_for(resource)
		root_path
	end
	
	protected
	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
	end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

	def create
		post_image = PostImage.find(params[:post_image_id])
		favorite = current_user.favorites.new(post_image_id: post_image.id)
		favorite.save
		redirect_to post_image_path(post_image)
	end

	def destroy
		post_image = PostImage.find(params[:post_image_id])
		favorite = current_user.favorites.find_by(post_image_id: post_image.id)
		favorite.destroy
		redirect_to post_image_path(post_image)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_action :authenticate_user!, except: [:index, :about]
	def index
		
	end
	def about
		
	end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController

	def create
		@post = PostImage.find(params[:post_image_id])
		@post_comment = current_user.post_comments.new(post_comment_params)
		@post_comment.post_image_id = @post.id
		@post_comment.save
		redirect_to post_image_path(@post)
	end

	private
	def post_comment_params
		params.require(:post_comment).permit(:comment)
	end
end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController

	def index
		@posts = PostImage.page(params[:page]).reverse_order
	end

	def show
		@post = PostImage.find(params[:id])
		@post_comments = @post.post_comments
		@post_comment = PostComment.new
	end

	def new
		@post = PostImage.new
	end

	def create
		@post = PostImage.new(post_params)
		@post.user_id = current_user.id
		if @post.save
			redirect_to post_images_path
		else
			render :new
		end
	end

	def edit
		@post = PostImage.find(params[:id])
	end

	def update
		@post = PostImage.find(params[:id])
		if @post.update(post_params)
			redirect_to post_image_path(@post.id)
		else
			render :edit
		end
	end

	def destroy
		@post = PostImage.find(params[:id])
		@post.destroy
		redirect_to post_images_path
	end

	private
	def post_params
		params.require(:post_image).permit(:title, :image, :caption, tag_ids: [])
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find(params[:id])
		@posts = @user.post_images.page(params[:page]).reverse_order
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		@user.update(user_params)
		if @user.save
			redirect_to user_path(@user.id)
		else
			render_to :edit
		end
	end

	def search
		if params[:name].present?
			@users = User.where("name LIKE ?", "%#{params[:name]}%")
		else
			@users = User.none
		end
	end


	private
	def user_params
		params.require(:user).permit(:name, :user_image, :introduction)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/about.html.erb
<div>
	About page
</div>

app/views/home/index.html.erb

	<div class="top-visual">
		<p>Top-visual</p>
		<div class="inup-btn">
			<div class="inup"><%= link_to "Sign_up", new_user_registration_path %></div>
			<div class="inup"><%= link_to "Log_in", new_user_session_path %></div>

		</div>
	</div>

app/views/layouts/_error_messages.html.erb


<% if model.errors.any? %>

	<ul>
		<% model.errors.full_messages.each do |msg| %>
			<li><%= message %></li>
		<% end %>
	</ul>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogSanpleApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/aa6a15dbff.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <% if user_signed_in? %>
      <!-- ログインあと -->
        <nav>
          <div class="nav-logo"><%= link_to "logo", post_images_path %></div>

          <ul class="nav-list">
            <li class="welcom">ようこそ <%= current_user.name %> さん</li>
            <li class="nav-item"><%= link_to "My page", user_path(current_user.id) %></li>
            <li class="nav-item"><%= link_to "探す", search_users_path %></li>
            <li class="nav-item"><%= link_to "投稿", new_post_image_path %></li>
            <li class="nav-item"><%= link_to "Log-out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </nav>
      <% else %>
      <!-- ログイン前 -->
        <nav>
            <div class="nav-logo">logo</div>

          <ul class="nav-list">
            <li class="nav-item"><%= link_to "Home", root_path %></li>
            <li class="nav-item"><%= link_to "About", home_about_path %></li>
            <li class="nav-item"><%= link_to "Sign_up", new_user_registration_path %></li>
            <li class="nav-item"><%= link_to "Log_in", user_session_path %></li>
          </ul>
        </nav>
      <% end %>
    </header><!-- /header -->


    <%= yield %>


    <footer>
      texitetxitetxi
    </footer>
  </body>
</html>

app/views/post_images/edit.html.erb
<div class="wrapper">
	<div class="content">
		<div class="edit-page">
			<h3 class="inup-head">** 編集 **</h3>
		<%= form_for(@post) do |f| %>

		<%= render 'layouts/error_messages', model: f.object %>
			<div class="field">
				<%= f.label :title %>
				<%= f.text_field :title %>
			</div>
			<div class="field">
				<%= f.label :image_id %>
				<%= f.attachment_field :image %>
			</div>
			<div class="field">
				<%= f.label :caption %><br>
				<%= f.text_area :caption %>
			</div>
			<div class='form-group'>
		        <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
		            <div class='form-check'>
		                <%= tag.label class: 'form-check-label' do %>
		                    <%= tag.check_box class: 'form-check-input' %>
		                    <%= tag.text %>
		                <% end %>
		            </div>
		        <% end %>
		    </div>
			<div class="field">
				<%= f.submit class:"in-btn"%>
			</div>
		<% end %>
		</div>

	<%= link_to "back", post_image_path(@post.id) %>
	<span> | </span>
	<%= link_to "index", post_images_path %>
	</div>
</div>

app/views/post_images/index.html.erb
<div class="main-visual">
	<p>post-index</p>
</div>

<div class="wrapper">
	<section class="image-index-content">
		<div>
			<h2 class="index-head">Blogs</h2>
			<table>
				<tbody class="blog-box">
					<% @posts.each do |post| %>
						<tr>
							<td class="blog-title"><%= link_to "#{post.title}", post_image_path(post.id) %>
							</td>
						</tr>
						<tr class="post-date">
							<td class="img-box"><%= attachment_image_tag post, :image, size:"300x200", fallback: "no_image.jpg" %>
							</td>
						</tr>
						<tr class="user-info">
							<td class="userphoto"><%= attachment_image_tag post.user, :user_image, fallback: "no_image.jpg", size:"40x40" %></td>
							<td class="username"><%= post.user.name %>
							</td>
							<td></td>
						</tr>
						<tr class="post-info">
							<td class="date"><%= post.created_at.strftime("%Y/%m/%d") %>
							</td>
							<td class="category"><% post.tags.each do |tag| %>
									<span class="badge badge-primary"><%= tag.name %></span>
								<% end %>
							</td>
						</tr>
						<tr>
							<td class="nice">
								<% if post.favorited_by?(current_user) %>
									<%= link_to post_image_favorites_path(post), method: :delete do %>
										<i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
										<%= post.favorites.count %> いいね
									<% end %>
								<% else %>
									<%= link_to post_image_favorites_path(post), method: :post do %>
										 <i class="fa fa-heart-o" aria-hidden="true"></i>
									 	<%= post.favorites.count %> いいね
									<% end %>
								<% end %>
							</td>
							<td class="comment"><%= link_to "#{post.post_comments.count} コメント", post_image_path(post.id) %>
							</td>
							<td></td>
						</tr>
						<tr>
							<td class="image-index-caption">
								<%= post.caption.truncate(50) %><br>
								<%= link_to "続きはこちら", post_image_path(post.id) %>
							</td>
						</tr>
					<% end %>
					<%= paginate @posts, class: "paginate" %>
				</tbody>
			</table>
		</div>
	</section>
</div><!--wrapper-->

app/views/post_images/new.html.erb

<div class="wrapper">
	<div class="content">
		<h3 class="inup-head">** 投稿 **</h3>
		<%= form_for(@post) do |f| %>
		<%= render 'layouts/error_messages', model: f.object %>

			<div class="field">
				<%= f.label :title %>
				<%= f.text_field :title %>
			</div>
			<div class="field">
				<%= f.label :image_id %>
				<%= f.attachment_field :image %>
			</div>
			<div class="field">
				<%= f.label :caption %><br>
				<%= f.text_area :caption %>
			</div>
			<div class="form-group">
				<%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
				    <div class="form-check">
				    	<%= tag.label class: "form-check-label" do %>
				    	    <%= tag.check_box class: "form-check-input" %>
				    	    <%= tag.text %>
				    	<% end %>
				    </div>
				<% end %>
			</div>
			<div class="field">
			<%= f.submit class:"in-btn" %>
			</div>
		<% end %>

		<%= link_to "back", post_images_path %>
	</div>
</div>

app/views/post_images/show.html.erb
<div class="post-image-show-visual">
	<p>画像　詳細</p>
</div>

<div class="wrapper">
	<div class="blog-show">
		<div class="blog-main">
			<h3 class="blog-show-title">
				<%= @post.title %>
			</h3>
			<div class="show-img-box">
				<%= attachment_image_tag @post, :image, size:"400x350",
				fallback:"no_image.jpg" %>
			</div>
			<div class="show-user-info">
				<div class="show-userphoto">
					<%= attachment_image_tag @post.user, :user_image, fallback:"no_image.jpg", size:"50x50" %>
				</div>
				<div class="show-username">
					<%= @post.user.name %>
				</div>
			</div>
			<div class="show-post-info">
				<div class="date">
					<%= @post.created_at.strftime("%Y/%m/%d") %>
				</div>
				<div class="category">
					<td class="category"><% @post.tags.each do |tag| %>
					<span class="badge badge-primary"><%= tag.name %></span>
					<% end %>
 				</div>
				<div class="nice">
					<%= @post.favorites.count %> いいね
				</div>
			</div>
			<div class="show-caption">
				<%= @post.caption %>
			</div>
			<div class="show-edit-destroy">
				<% if @post.user == current_user %>
					<%= link_to "編集", edit_post_image_path(@post.id), class:"btn" %>
					<%= link_to "削除", post_image_path(@post.id), method: :delete, "data-confirm" => "本当に削除しますか？", class:"btn" %>
				<% end %>
			</div>

			<div class="image-show-comment">
				<h3>コメント</h3>
				<table>								<% @post.post_comments.each do |post_comment| %>
					<tbody>
						<tr class="user-info">
							<td class="comment-user"><%= attachment_image_tag post_comment.user, :user_image, fallback:"no_image", size:"40x40" %></td>
							<td><%= link_to "#{post_comment.user.name}", user_path(post_comment.user.id) %>
							</td>
							<td><%= post_comment.created_at.strftime("%Y/%m/%d") %>
							</td>
						</tr>
						<tr class="comment-text">
							<td><%= post_comment.comment %>
							</td>
						</tr>
					</tbody>
				<% end %>
				</table>
			</div><!--comment-->
		</div><!--blogmain-->

		<div class="sidebar postcomment">
			<p>コメントしてね！！</p>

			<%= form_for [@post, @post_comment] do |f| %>
			<%= render 'layouts/error_messages', model: f.object %>

				<%= f.text_area :comment, rows:"5", placeholder:"コメント記入" %>
				<%= f.submit "投稿" %>
			<% end %>
		</div><!--postcomment-->
	</div><!--blog-show-->
</div>

app/views/users/edit.html.erb
<div class="wrapper">
	<div class="content">

		<div class="user-edit">
			<h3 class="inup-head">** User 編集 **</h3>
			<%= form_for(@user) do |f| %>
			<%= render 'layouts/error_messages', model: f.object %>
				<div class="field">
					<%= f.label :name %>
					<%= f.text_field :name %>
				</div>
				<div class="field">
					<%= f.label :user_image %>
					<%= f.attachment_field :user_image %>
				</div>
				<div class="field">
					<%= f.label :introduction %>
					<%= f.text_area :introduction %>
				</div>
				<div class="field">
					<%= f.submit class:"in-btn" %>
				</div>
			<% end %>
		</div>

		<%= link_to "back", user_path(@user.id) %>
	</div>
</div>

app/views/users/search.html.erb
<div class="wrapper">
	<div class="content">
		<h3 class="inup-head">** 検索 **</h3>
		<%= form_with url: search_users_path, method: :get, local: true do |f| %>
			<div class="field">
				<%= f.text_field :name, placefolder:"名前入れてね" %>
			</div>
			<div class="field">
				<%= f. submit :search, class:"in-btn" %>
			</div>
		<% end %>
		<table>
			<thead>
				<tr>
					<th></th>
					<th>Name</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				<% @users.each do |user| %>
				<tr>
					<td><%= attachment_image_tag user, :user_image, size:"40x40", fallback:"no_image.jpg" %></td>
					<td><%= user.name %></td>
					<td><%= link_to "that page", user_path(user.id) %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/users/show.html.erb
<div class="main-visual">
	<p>user-show</p>
</div>

<div class="wrapper">
	<div class="user-box">
		<div class="user-profile">
			<div class="user-img">
				<%= attachment_image_tag @user, :user_image, fallback:"no_image.jpg", size:"100x100" %>
			</div>
			<div class="introduction">
			<%= @user.name %><br>
			<%= @user.introduction %>
			</div>
			<%= link_to "あたらしい投稿", new_post_image_path %>
		</div>


		<div class="user-blog">
		<% @posts.each do |post| %>
			<h3 class="blog-title">
				<%= link_to "#{post.title}", post_image_path(post.id) %>
			</h3>
			<div class="img-box">
				<%= attachment_image_tag post, :image, fallback:"no_image.jpg", size:"300x200" %>
			</div>
			<div class="post-info">
				<div class="date">
					<%= post.created_at.strftime("%Y/%m/%d") %>
				</div>
				<div class="category">
					<td class="category"><% post.tags.each do |tag| %>
						<span class="badge badge-primary"><%= tag.name %></span>
					<% end %>
				</div>
				<div class="nice">
					<%= post.favorites.count %> いいね
				</div>
				<div class="comment">
					<%= link_to "#{post.post_comments.count} コメント", post_image_path(post.id) %>
				</div>
			</div>
			<div class="caption">
				<%= post.caption.truncate(50) %>
				<%= link_to "続きはこちら", post_image_path(post.id) %>
			</div>
		<% end %>
		<%= paginate @posts, class: "paginate" %>
		</div>
	</div>
</div>